[workspace]
members = [
    "storage-benchmarks",
    "test-storage-tree",
    "vanilla-storage-tree",
]
resolver = "2"

# [workspace.dependencies]
# tokio = { version = "1.42.0", features = ["full"] }

